# toy_en_de.yaml

## IO
save_data: run
overwrite: False
seed: 3435
report_every: 100
valid_metrics: ["BLEU"]

## Vocab
src_vocab: run/source.vocab
tgt_vocab: run/target.vocab
src_vocab_size: 5000
tgt_vocab_size: 5000
vocab_size_multiple: 8
src_words_min_frequency: 2
tgt_words_min_frequency: 2
share_vocab: True
n_sample: 0

# Corpus opts
data:
    corpus_1:
        path_src: file.src-filtered.src.subword.train
        path_tgt: file.trg-filtered.trg.subword.train
    valid:
        path_src: file.src-filtered.src.subword.dev
        path_tgt: file.trg-filtered.trg.subword.dev

# Data transforms
transforms: [sentencepiece, filtertoolong]
transforms_configs:
  sentencepiece:
    src_subword_model: source.model
    tgt_subword_model: target.model
  filtertoolong:
    src_seq_length: 150
    tgt_seq_length: 150

# Model architecture
model:
  architecture: transformer
  encoder:
    layers: 6
  decoder:
    layers: 6
  heads: 8
  hidden_size: 512
  transformer_ff: 2048
  embeddings:
    word_vec_size: 512
    position_encoding: true

# Training
training:
  # Single GPU
  model_path: models/model.fren
  keep_checkpoint: 10
  save_checkpoint_steps: 500
  average_decay: 0
  train_steps: 1000
  valid_steps: 500
  bucket_size: 262144
  num_workers: 4
  prefetch_factor: 400
  world_size: 1
  gpu_ranks: [0]
  # Batching
  batch_type: tokens
  batch_size: 4096
  valid_batch_size: 4096
  batch_size_multiple: 8
  accum_count: [10]
  accum_steps: [0]
  # Optimizer
  compute_dtype: fp16
  optim: adamw
  use_amp: False
  learning_rate: 2
  warmup_steps: 8000
  decay_method: noam
  adam_beta2: 0.998
  # Hyperparams
  dropout_steps: [0]
  dropout: [0.1]
  attention_dropout: [0.1]
  max_grad_norm: 0
  label_smoothing: 0.1
  param_init_method: xavier_uniform
  normalization: tokens
